= Lim Wan Ching - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: FlashCards

---

== Overview

FlashCards is a desktop application used for helping secondary school students memorise their content.
It also helps them manage all their notes by keeping them in a single application. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*: Added the ability for *GUI* to *display only flashcards belonging to the selected subject*
** What it does: allows the user to undo all previous commands one at a time. Preceding undo commands can be reversed by using the redo command.
** Justification: This feature improves the product significantly because a user can make mistakes in commands and the app should provide a convenient way to rectify them.
** Highlights: This enhancement affects existing commands and commands to be added in future. It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changes to existing commands.
** Credits: _{mention here if you reused any code/ideas from elsewhere or if a third-party library is heavily used in the feature so that a reader can make a more accurate judgement of how much effort went into the feature}_

* *Minor enhancement*: Added colours to different subject tags so the same subject will have the same colour. This helps users to differentiate flashcards better based on the subject when all flashcards are listed.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Managed relevant documentations (e.g. UserGuide, AboutUs etc.) by ensuring everything is correct and well-documented.
** Enhancements to existing features:
*** Updated tags to have different colours (Pull requests https://github.com[#33], https://github.com[#34])
*** Enhanced `AddCommand()` to check for unique subjects before adding the subject to a `UniqueSubjectList` object
** Documentation:
*** Did cosmetic tweaks to existing contents of the User and Developer Guide: https://github.com[#14]
**** Ensured the consistency in language
**** Ensured there were no spelling and grammatical errors
**** Tidied up the formatting of documents
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]


== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=add]

include::../UserGuide.adoc[tag=edit]

include::../UserGuide.adoc[tag=delete]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=undoredo]

include::../DeveloperGuide.adoc[tag=dataencryption]


== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
