= Lim Wan Ching - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: FlashCards

---

== Overview

FlashCards is a desktop application used for helping secondary school students memorise their content.
It also helps them manage all their notes by keeping them in a single application. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*: Made enhancement to *GUI*
** What it does: Allows the user to select a certain subject and only flashcards belonging to that subject will be listed.
** Justification: This feature helps the user filter flashcards based on their subject with the ability to click via the GUI.
It can help them to focus on a particular subject's notes when studying.
** Highlights: This enhancement affects the existing GUI and `add` command.
It gives the user a better user experience and helps them study more effectively.
Furthermore, no separate storage is needed even though the subject list is seemingly saved every time the user exits.
On the next start up, the subject panel will contain the subject list that existed before the user exited the application.

* *Minor enhancement*: Added colours to different subject tags so the same subject will have the same colour. This helps users to differentiate flashcards better based on the subject when all flashcards are listed.

* *Code contributed*: [https://github.com/cs2113-ay1819s2-m11-3/main/pull/73[Functional code]]

* *Other contributions*:

** Project management:
*** Managed relevant documentations (e.g. User Guide etc.) by ensuring everything is correct and well-documented.
** Enhancements to existing features:
*** Updated tags to have different colours (Pull request https://github.com/cs2113-ay1819s2-m11-3/main/pull/6[#6])
*** Enhanced `AddCommand()` to check for unique subjects before adding the subject to a `UniqueSubjectList` object
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com/cs2113-ay1819s2-m11-3/main/pull/77/files[#77]
**** Ensured the consistency in language
**** Ensured there were no spelling and grammatical errors
**** Tidied up the formatting of documents
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com/cs2113-ay1819s2-m11-3/main/pull/30[#30] https://github.com/cs2113-ay1819s2-m11-3/main/pull/80[#80] https://github.com/cs2113-ay1819s2-m11-3/main/pull/86[#86]


== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=add]

include::../UserGuide.adoc[tag=edit]

include::../UserGuide.adoc[tag=delete]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=quizzingbysubject]
